apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: balance-fit-dr

namespace: balance-fit-dr

resources:
  - ../../base
  - namespace.yaml
  - route.yaml
  - secrets/mysql-secret.yaml

# DR environment uses single replicas for cost optimization
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: nginx
    spec:
      replicas: 1
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: efit
    spec:
      replicas: 1
  - |-
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: app-data
    spec:
      resources:
        requests:
          storage: 10Gi
  - |-
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: mysql-data
    spec:
      resources:
        requests:
          storage: 20Gi

commonLabels:
  environment: dr
  
commonAnnotations:
  environment: dr
  cluster: ocp-dr
  
images:
  - name: quay.apps.ocp.kohlerco.com/kohler-base-images/efit
    newTag: "latest"
