apiVersion: apps/v1
kind: Deployment
metadata:
  name: efit
  labels:
    app: efit
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: efit
  template:
    metadata:
      labels:
        app: efit
        component: backend
    spec:
      serviceAccountName: default
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: efit
        image: quay.apps.ocp.kohlerco.com/kohler-base-images/efit:latest
        ports:
        - containerPort: 9000
          name: php-fpm
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: DB_HOST
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: DB_DATABASE
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: DB_PASSWORD
        volumeMounts:
        - name: app-data
          mountPath: /code
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: app-data
