apiVersion: v1
kind: Service
metadata:
  name: efit
  labels:
    app: efit
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: php-fpm
  selector:
    app: efit
