apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
    component: database
type: Opaque
stringData:
  DB_USERNAME: "efit"
  DB_PASSWORD: "inicial123"
  MYSQL_ROOT_PASSWORD: "rootpassword123"
