apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data
  labels:
    app: balance-fit
    component: storage
spec:
  accessModes:
  - ReadWriteOnce  resources:
    requests:
      storage: 5Gi
  storageClassName: ocs-storagecluster-ceph-rbd
